{{- range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.servicename }}
  labels:
    projectname: {{ $.Values.projectname }}
    environment: {{ $.Values.environment }}
    servicename: {{ $service.servicename }}
spec:
  type: {{ $service.service.type }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    projectname: {{ $.Values.projectname }}
    environment: {{ $.Values.environment }}
    servicename: {{ $service.servicename }}
---
{{- end }}