# Default values for coins-dev-uat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

projectname: "dockercoins"

#environment default values : coins-dev ,  or --set  environment=xxx
environment: "dev"

services:
  webui:
    servicename: webui
    replicaCount: 1

    deployment:
      enabled: true

    image:
      repository: 127.0.0.1:30587/webui
      tag: v0.1
      pullPolicy: IfNotPresent

    service:
      type: NodePort
      port: 80

    ingress:
      enabled: true
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"

  hasher:
    servicename: hasher
    replicaCount: 1

    deployment:
      enabled: true
      
    image:
      repository: 127.0.0.1:30587/hasher
      tag: v0.1
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: false
      annotations: {}
     
  worker:
    servicename: worker
    replicaCount: 1

    deployment:
      enabled: true
      
    image:
      repository: 127.0.0.1:30587/worker
      tag: v0.1
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: false
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"

  rng:
    servicename: rng

    deployment:
      enabled: false
      
    image:
      repository: 127.0.0.1:30587/rng
      tag: v0.1
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: false
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"